# Generated by Django 6.0.1 on 2026-03-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("load", "Load"), ("recovery", "Recovery")],
                        max_length=10,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("study", "Study"),
                            ("society", "Society"),
                            ("sleep", "Sleep"),
                            ("rest", "Rest"),
                            ("sport", "Sport"),
                            ("walking", "Walking"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("value", models.FloatField(default=1.0)),
                ("is_custom", models.BooleanField(default=False)),
                ("is_editable", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EnergyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("load", "Load"), ("recovery", "Recovery")],
                        max_length=10,
                    ),
                ),
                ("activity_type", models.CharField(max_length=32)),
                ("activity_coef", models.FloatField()),
                ("subjective_coef", models.FloatField()),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("energy_before", models.FloatField()),
                ("energy_after", models.FloatField()),
                ("acute_before", models.FloatField()),
                ("acute_after", models.FloatField()),
                ("chronic_before", models.FloatField()),
                ("chronic_after", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("params_json", models.JSONField()),
                ("version", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
