# Generated by Django 6.0.1 on 2026-01-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(default="", max_length=32)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("study", "Study"),
                            ("society", "Society"),
                            ("sleep", "Sleep"),
                            ("rest", "Rest"),
                            ("sport", "Sport"),
                        ],
                        max_length=32,
                    ),
                ),
                ("base_coef", models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name="energyevent",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("study", "Study"),
                    ("society", "Society"),
                    ("sleep", "Sleep"),
                    ("rest", "Rest"),
                    ("sport", "Sport"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="base_coef",
            field=models.FloatField(default=1.0),
        ),
    ]
