# Generated by Django 6.0.1 on 2026-03-02 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("energy", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitytype",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_type",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="energy_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="params_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="energy.modelparams"
            ),
        ),
        migrations.AddIndex(
            model_name="energyevent",
            index=models.Index(
                fields=["user", "started_at"], name="energy_ener_user_id_edf085_idx"
            ),
        ),
    ]
