# Generated by Django 6.0.1 on 2026-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytype",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
