# Generated by Django 6.0.1 on 2026-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0002_activitytype_energyevent_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytype",
            name="category",
            field=models.CharField(
                choices=[("load", "Load"), ("recovery", "Recovery")], max_length=32
            ),
        ),
    ]
