# Generated by Django 6.0.1 on 2026-03-03 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0003_alter_activitytype_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitytype",
            options={"ordering": ["category", "name"]},
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_types",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activitytype",
            unique_together={("user", "name")},
        ),
    ]
