# Generated by Django 6.0.1 on 2026-01-18 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0003_alter_activitytype_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="energyevent",
            old_name="base_coef",
            new_name="activity_coef",
        ),
    ]
