# Generated by Django 6.0.1 on 2026-03-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0004_alter_activitytype_options_alter_activitytype_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytype",
            name="category",
            field=models.CharField(
                choices=[
                    ("load", "Load"),
                    ("recovery", "Recovery"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("load", "Load"),
                    ("recovery", "Recovery"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
    ]
