# Generated by Django 6.0.1 on 2026-01-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0004_rename_base_coef_energyevent_activity_coef"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activitytype",
            old_name="base_coef",
            new_name="activity_coef",
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="category",
            field=models.CharField(
                choices=[("load", "Load"), ("recovery", "Recovery")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="code",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("study", "Study"),
                    ("society", "Society"),
                    ("sleep", "Sleep"),
                    ("rest", "Rest"),
                    ("sport", "Sport"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="activity_coef",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="activity_type",
            field=models.CharField(max_length=32),
        ),
    ]
