# Generated by Django 6.0.1 on 2026-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0005_rename_base_coef_activitytype_activity_coef_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyevent",
            name="subjective_coef",
            field=models.FloatField(default=1.0),
        ),
    ]
