# Generated by Django 6.0.1 on 2026-03-04 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0005_alter_activitytype_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyevent",
            name="break_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="continuous_load_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="sleep_minutes",
            field=models.IntegerField(default=0),
        ),
    ]
