# Generated by Django 6.0.1 on 2026-03-05 14:12
import django.contrib.postgres.constraints
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0006_energyevent_break_minutes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="energyevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("started_at__lt", models.F("ended_at"))),
                name="event_start_before_end",
            ),
        ),
        migrations.AddConstraint(
            model_name="energyevent",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        models.Func(
                            models.F("started_at"),
                            models.F("ended_at"),
                            function="tstzrange",
                        ),
                        "&&",
                    ),
                    ("user", "="),
                ],
                name="prevent_event_overlap",
            ),
        ),
    ]
