# Generated by Django 6.0.1 on 2026-05-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0007_energyevent_event_start_before_end_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="energyevent",
            name="activity_type",
        ),
        migrations.RemoveField(
            model_name="energyevent",
            name="event_type",
        ),
        migrations.AddField(
            model_name="energyevent",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="energy.activitytype",
            ),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="activity_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("load", "Load"),
                    ("recovery", "Recovery"),
                    ("system", "System"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="activity_name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
