# Generated by Django 6.0.1 on 2026-01-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0007_personalactivityprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="energyevent",
            name="base_coef",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="energyevent",
            name="personal_coef",
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="activity_coef",
            field=models.FloatField(default=1.0),
        ),
    ]
