# Generated by Django 6.0.1 on 2026-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0008_energyevent_base_coef_energyevent_personal_coef_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyevent",
            name="activity_coef",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="base_coef",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="personal_coef",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="subjective_coef",
            field=models.FloatField(),
        ),
    ]
