# Generated by Django 6.0.1 on 2026-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0008_remove_energyevent_activity_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyevent",
            name="activity_category",
            field=models.CharField(
                choices=[
                    ("load", "Load"),
                    ("recovery", "Recovery"),
                    ("system", "System"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="energyevent",
            name="activity_name",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
