# Generated by Django 6.0.1 on 2026-05-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0009_alter_energyevent_activity_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="energyevent",
            name="activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="energy.activitytype",
            ),
        ),
    ]
