# Generated by Django 6.0.1 on 2026-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0009_alter_energyevent_activity_coef_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCoef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coef_type", models.CharField(max_length=24)),
                ("value", models.FloatField(default=1.0)),
            ],
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="code",
            field=models.CharField(
                choices=[
                    ("work", "Work"),
                    ("study", "Study"),
                    ("society", "Society"),
                    ("sleep", "Sleep"),
                    ("rest", "Rest"),
                    ("sport", "Sport"),
                    ("walking", "Walking"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
