# Generated by Django 6.0.1 on 2026-02-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("energy", "0010_basecoef_alter_activitytype_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basecoef",
            name="coef_type",
            field=models.CharField(
                choices=[("load", "Load"), ("recovery", "Recovery")],
                max_length=24,
                unique=True,
            ),
        ),
    ]
