## Generated by Django 6.0.1 on 2026-05-06 19:51
from django.db import migrations

DEFAULT_PARAMS = {
    "sleep_k": 0.85,
    "clamp_max": 1.0,
    "clamp_min": 0.05,
    "recovery_k_e": 0.0022,
    "chronic_power": 1.2,
    "acute_smoothing": 0.1,
    "load_energy_rate": 0.0023,
    "recovery_midpoint": 10,
    "sleep_acute_decay": 0.03,
    "recovery_exp_power": 1.25,
    "recovery_steepness": 0.3,
    "strain_growth_coef": 0.05,
    "circadian_amplitude": 0.02,
    "load_chronic_growth": 0.002,
    "sleep_chronic_decay": 0.002,
    "recovery_acute_decay": 0.03,
    "sleep_midpoint_hours": 4.0,
    "circadian_phase_shift": -3,
    "load_continuous_factor": 0.01,
    "recovery_chronic_decay": 0.002,
    "sleep_energy_multiplier": 0.4,
    "sleep_recovery_midpoint": 10,
    "sleep_recovery_steepness": 0.3,
    "recovery_energy_multiplier": 0.3,
}


def create_model_params(apps, schema_editor):
    ModelParams = apps.get_model("energy", "ModelParams")

    if ModelParams.objects.exists():
        return

    ModelParams.objects.create(
        params_json=DEFAULT_PARAMS,
        version=1,
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0010_alter_energyevent_activity"),
    ]

    operations = [
        migrations.RunPython(create_model_params, reverse_func),
    ]
