# Generated by Django 6.0.1 on 2026-05-07 20:38

from django.db import migrations


def normalize_events(apps, schema_editor):
    EnergyEvent = apps.get_model("energy", "EnergyEvent")
    for event in EnergyEvent.objects.all():
        event.started_at = event.started_at.replace(microsecond=0)
        event.ended_at = event.ended_at.replace(microsecond=0)
        event.save(update_fields=["started_at", "ended_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("energy", "0011_seed_model_params"),
    ]

    operations = [
        migrations.RunPython(normalize_events),
    ]
